insert into product  (id, product_name, price, specification, quantity) values (1, 'Raspberries - Fresh', 97, 'Cl skul fx NEC-deep coma', 61);
insert into product (id, product_name, price, specification, quantity) values (2, 'Pasta - Lasagna, Dry', 66, 'AMI inferopost, initial', 84);
insert into product (id, product_name, price, specification, quantity) values (3, 'Apple - Royal Gala', 70, 'Open wound trachea-compl', 70);
insert into product (id, product_name, price, specification, quantity) values (4, 'Juice - Ocean Spray Kiwi', 89, 'Opn skull/oth fx-concuss', 22);
insert into product (id, product_name, price, specification, quantity) values (5, 'Beef - Bones, Marrow', 92, 'Central cord syn/t7-t12', 19);
insert into product (id, product_name, price, specification, quantity) values (6, 'Bagel - Whole White Sesame', 57, 'Acc poisoning-antimony', 5);
insert into product (id, product_name, price, specification, quantity) values (7, 'Oregano - Dry, Rubbed', 25, 'Taenia saginata infect', 86);
insert into product (id, product_name, price, specification, quantity) values (8, 'Pork - Ground', 52, 'Dev open/close mandible', 93);
insert into product (id, product_name, price, specification, quantity) values (9, 'Fish - Artic Char, Cold Smoked', 46, 'Old laceration of vulva', 5);
insert into product (id, product_name, price, specification, quantity) values (10, 'Halibut - Fletches', 45, 'Malig neo biliary NEC', 1);
insert into product (id, product_name, price, specification, quantity) values (11, 'Tortillas - Flour, 12', 58, 'Prs ara w ntr wo inf/st', 71);
insert into product (id, product_name, price, specification, quantity) values (12, 'Cakes Assorted', 34, 'TB of eye-histo dx', 87);
insert into product (id, product_name, price, specification, quantity) values (13, 'Sage - Fresh', 39, 'Cl skull base fx/hem NEC', 97);
insert into product (id, product_name, price, specification, quantity) values (14, 'Wine - Zinfandel Rosenblum', 66, 'Drug withdrawal', 7);
insert into product (id, product_name, price, specification, quantity) values (15, 'Lobster - Live', 14, 'Joint replaced hip', 40);
insert into product (id, product_name, price, specification, quantity) values (16, 'Watercress', 76, 'RR coll w oth obj-pedest', 22);
insert into product (id, product_name, price, specification, quantity) values (17, 'Black Currants', 87, 'Conn''s syndrome', 48);
insert into product (id, product_name, price, specification, quantity) values (18, 'Crab Meat Claw Pasteurise', 99, 'TB of joint NEC-cult dx', 19);
insert into product (id, product_name, price, specification, quantity) values (19, 'Lamb Shoulder Boneless Nz', 28, 'Abscess of eyelid', 42);
insert into product (id, product_name, price, specification, quantity) values (20, 'Ecolab - Hobart Upr Prewash Arm', 78, 'Oth spcf deformity head', 62);
insert into product (id, product_name, price, specification, quantity) values (21, 'Thyme - Lemon, Fresh', 34, 'Ac leu un cl wo ach rmsn', 28);
insert into product (id, product_name, price, specification, quantity) values (22, 'Fennel', 47, 'Surgical convalescence', 65);
insert into product (id, product_name, price, specification, quantity) values (23, 'Basil - Pesto Sauce', 83, 'Problem w aged parent', 53);
insert into product (id, product_name, price, specification, quantity) values (24, 'Coffee - Colombian, Portioned', 95, 'Gangr incisional hernia', 28);
insert into product (id, product_name, price, specification, quantity) values (25, 'Calypso - Pineapple Passion', 99, 'Trans cereb ischemia NEC', 63);
insert into product (id, product_name, price, specification, quantity) values (26, 'Wine - Maipo Valle Cabernet', 55, 'Peripartum card-postpart', 77);
insert into product (id, product_name, price, specification, quantity) values (27, 'Paper - Brown Paper Mini Cups', 97, 'Hair transplant', 60);
insert into product (id, product_name, price, specification, quantity) values (28, 'Yogurt - Cherry, 175 Gr', 19, 'Path fx oth spcf prt fmr', 15);
insert into product (id, product_name, price, specification, quantity) values (29, 'Watercress', 19, 'Inj brnch sup mesent art', 68);
insert into product (id, product_name, price, specification, quantity) values (30, 'Ice Cream Bar - Oreo Sandwich', 55, 'Comp-heart valve prosth', 6);
insert into product (id, product_name, price, specification, quantity) values (31, 'Cheese - La Sauvagine', 43, 'Water/watercraft', 19);
insert into product (id, product_name, price, specification, quantity) values (32, 'Muffin Batt - Blueberry Passion', 80, 'Lactation fail-antepart', 10);
insert into product (id, product_name, price, specification, quantity) values (33, 'Clam - Cherrystone', 83, 'Open wound palate-compl', 80);
insert into product (id, product_name, price, specification, quantity) values (34, 'Flavouring - Orange', 67, 'Acute iridocyclitis NOS', 86);
insert into product (id, product_name, price, specification, quantity) values (35, 'Tea - Green', 67, 'Mlt opn wnd shldr w tend', 28);
insert into product (id, product_name, price, specification, quantity) values (36, 'Cheese - Pied De Vents', 1, 'Endocrine disorder NOS', 40);
insert into product (id, product_name, price, specification, quantity) values (37, 'Pasta - Fusili Tri - Coloured', 60, 'Loose body-joint NEC', 27);
insert into product (id, product_name, price, specification, quantity) values (38, 'Wine - White, Riesling, Semi - Dry', 17, 'Bipol I manic-sev w psy', 94);
insert into product (id, product_name, price, specification, quantity) values (39, 'Trout - Smoked', 77, 'Family history glaucoma', 14);
insert into product (id, product_name, price, specification, quantity) values (40, 'Durian Fruit', 23, 'Cl skl w oth fx-coma NOS', 75);
insert into product (id, product_name, price, specification, quantity) values (41, 'Turkey - Breast, Double', 66, 'T7-t12 fx-cl/ant crd syn', 70);
insert into product (id, product_name, price, specification, quantity) values (42, 'Tarragon - Primerba, Paste', 72, 'Ulcerative blepharitis', 89);
insert into product (id, product_name, price, specification, quantity) values (43, 'Foam Espresso Cup Plain White', 81, 'Cerv incompet preg-unsp', 74);
insert into product (id, product_name, price, specification, quantity) values (44, 'Glass Clear 8 Oz', 12, 'Postsurg hypoinsulinemia', 1);
insert into product (id, product_name, price, specification, quantity) values (45, 'Chips - Assorted', 70, 'Preg w hx-trophoblas dis', 3);
insert into product (id, product_name, price, specification, quantity) values (46, 'Apricots Fresh', 44, 'Insect bite hand', 24);
insert into product (id, product_name, price, specification, quantity) values (47, 'Oil - Shortening,liqud, Fry', 79, 'Macrocheilia', 54);
insert into product (id, product_name, price, specification, quantity) values (48, 'Apples - Sliced / Wedge', 17, 'Peyronie''s disease', 76);
insert into product (id, product_name, price, specification, quantity) values (49, 'Cream - 10%', 30, 'Amebiasis NOS', 90);
insert into product (id, product_name, price, specification, quantity) values (50, 'Swiss Chard', 28, 'Renal failure NOS', 23);
insert into product (id, product_name, price, specification, quantity) values (51, 'Beer - Fruli', 91, 'Lac eyelid inv lacrm pas', 55);
insert into product (id, product_name, price, specification, quantity) values (52, 'Table Cloth 90x90 White', 85, 'Abdmnal pain rt lwr quad', 59);
insert into product (id, product_name, price, specification, quantity) values (53, 'Cocoa Feuilletine', 58, '1st deg burn abdomn wall', 18);
insert into product (id, product_name, price, specification, quantity) values (54, 'Wine - Sawmill Creek Autumn', 33, 'Adv eff bcg vaccine', 48);
insert into product (id, product_name, price, specification, quantity) values (55, 'Triple Sec - Mcguinness', 86, 'Acc poison-analgesic NEC', 63);
insert into product (id, product_name, price, specification, quantity) values (56, 'Wine - Sogrape Mateus Rose', 43, 'Aortic aneurysm, syphil', 80);
insert into product (id, product_name, price, specification, quantity) values (57, 'Pastry - Trippleberry Muffin - Mini', 70, 'Oth mal neo skn site NOS', 97);
insert into product (id, product_name, price, specification, quantity) values (58, 'Cakes Assorted', 91, 'Trnspl status-bne marrow', 61);
insert into product (id, product_name, price, specification, quantity) values (59, 'Sausage - Blood Pudding', 99, 'Fall on/from train-empl', 58);
insert into product (id, product_name, price, specification, quantity) values (60, 'Cookie Dough - Peanut Butter', 64, 'Deep 3rd deg burn ankle', 69);
insert into product (id, product_name, price, specification, quantity) values (61, 'Pepper - Green, Chili', 59, 'Contusion trunk NOS', 49);
insert into product (id, product_name, price, specification, quantity) values (62, 'Cheese - Victor Et Berthold', 3, 'Vasc dementia w delirium', 47);
insert into product (id, product_name, price, specification, quantity) values (63, 'Pickerel - Fillets', 15, 'Malig neo tongue NEC', 3);
insert into product (id, product_name, price, specification, quantity) values (64, 'Foam Tray S2', 29, 'Indeterminate leprosy', 86);
insert into product (id, product_name, price, specification, quantity) values (65, 'Beef - Top Sirloin', 29, 'Chronic dacryocystitis', 22);
insert into product (id, product_name, price, specification, quantity) values (66, 'Tea - Apple Green Tea', 16, 'Hem early preg NEC-unsp', 26);
insert into product (id, product_name, price, specification, quantity) values (67, 'Glaze - Apricot', 76, 'Anphylct react food NOS', 49);
insert into product (id, product_name, price, specification, quantity) values (68, 'Carrots - Purple, Organic', 91, 'Abrasion finger', 91);
insert into product (id, product_name, price, specification, quantity) values (69, 'Ice Cream - Super Sandwich', 53, 'Blister forearm-infected', 89);
insert into product (id, product_name, price, specification, quantity) values (70, 'Cheese - Mozzarella, Buffalo', 36, 'Oth vehicle acc NEC', 92);
insert into product (id, product_name, price, specification, quantity) values (71, 'Salmon - Smoked, Sliced', 73, 'Atony of bladder', 25);
insert into product (id, product_name, price, specification, quantity) values (72, 'Cookie Dough - Peanut Butter', 70, 'Elderly multigravida-del', 88);
insert into product (id, product_name, price, specification, quantity) values (73, 'Island Oasis - Magarita Mix', 96, 'Acromegaly and gigantism', 25);
insert into product (id, product_name, price, specification, quantity) values (74, 'Syrup - Chocolate', 6, 'Bone infect NEC-pelvis', 12);
insert into product (id, product_name, price, specification, quantity) values (75, 'Clams - Canned', 1, 'TB esophagus-no exam', 78);
insert into product (id, product_name, price, specification, quantity) values (76, 'Bread - Malt', 9, 'Unstable lie-unspecified', 79);
insert into product (id, product_name, price, specification, quantity) values (77, 'Salami - Genova', 66, 'Dysenter arthrit-pelvis', 51);
insert into product (id, product_name, price, specification, quantity) values (78, 'Beans - Black Bean, Canned', 72, 'Abrasion hand-infected', 90);
insert into product (id, product_name, price, specification, quantity) values (79, 'Turkey - Oven Roast Breast', 54, 'Hx-radiogrphc dye allrgy', 14);
insert into product (id, product_name, price, specification, quantity) values (80, 'Figs', 21, 'Preterm NEC 2000-2499g', 19);
insert into product (id, product_name, price, specification, quantity) values (81, 'Coffee - Ristretto Coffee Capsule', 42, 'Hordeolum internum', 74);
insert into product (id, product_name, price, specification, quantity) values (82, 'Garlic Powder', 9, 'Anphylct react food addv', 28);
insert into product (id, product_name, price, specification, quantity) values (83, 'Capon - Breast, Wing On', 75, 'Venous thrombosis NOS', 85);
insert into product (id, product_name, price, specification, quantity) values (84, 'Table Cloth 144x90 White', 83, 'Ulceratve colitis unspcf', 63);
insert into product (id, product_name, price, specification, quantity) values (85, 'Apples - Sliced / Wedge', 82, 'Screen mammogram NEC', 73);
insert into product (id, product_name, price, specification, quantity) values (86, 'Wine - Magnotta - Belpaese', 1, 'Pain in limb', 19);
insert into product (id, product_name, price, specification, quantity) values (87, 'Coffee - Irish Cream', 58, 'Long-term use of aspirin', 26);
insert into product (id, product_name, price, specification, quantity) values (88, 'Bar - Granola Trail Mix Fruit Nut', 69, 'Dancing', 48);
insert into product (id, product_name, price, specification, quantity) values (89, 'Carbonated Water - Wildberry', 26, 'BMI 33.0-33.9,adult', 73);
insert into product (id, product_name, price, specification, quantity) values (90, 'Beer - Blue', 2, 'Symbolic dysfunction NEC', 5);
insert into product (id, product_name, price, specification, quantity) values (91, 'Beer - Maudite', 37, 'Colostomy status', 20);
insert into product (id, product_name, price, specification, quantity) values (92, 'Wine - Jafflin Bourgongone', 13, 'Ac follic conjunctivitis', 18);
insert into product (id, product_name, price, specification, quantity) values (93, 'Pork - Side Ribs', 57, 'Spermatocele', 3);
insert into product (id, product_name, price, specification, quantity) values (94, 'Sandwich Wrap', 24, 'Contusion of finger', 73);
insert into product (id, product_name, price, specification, quantity) values (95, 'Beer - Blue Light', 53, 'Fx cuneiform, foot-open', 74);
insert into product (id, product_name, price, specification, quantity) values (96, 'Southern Comfort', 19, 'Traumatic anuria', 87);
insert into product (id, product_name, price, specification, quantity) values (97, 'Pear - Prickly', 60, 'Athrsc extrm ntv art oth', 40);
insert into product (id, product_name, price, specification, quantity) values (98, 'Chinese Foods - Chicken', 67, 'Peroxisomal disorders', 55);
insert into product (id, product_name, price, specification, quantity) values (99, 'Creme De Banane - Marie', 5, 'Wtrcrft acc NEC-pers NOS', 8);
insert into product (id, product_name, price, specification, quantity) values (100, 'Daves Island Stinger', 36, 'Opn skul vlt fx-coma NOS', 31);
