insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (1, 'Longos - Burritos', 81641, 'Malignant neoplasm of axillary tail of left female breast', 36, 3, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (2, 'Beans - Wax', 15615, 'Nondisp fx of shaft of fifth MC bone, left hand, sequela', 32, 4, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (3, 'Eggs - Extra Large', 3931, 'Cont preg aft uterin dth of one fts or more, third tri, unsp', 38, 4, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (4, 'Capicola - Hot', 64889, 'Unspecified mastoiditis', 26, 1, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (5, 'Tomatoes - Vine Ripe, Red', 7040, 'Corrosion of unspecified degree of chest wall, subs encntr', 33, 1, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (6, 'Coffee - Beans, Whole', 85162, 'Laceration with foreign body, right lower leg, init encntr', 36, 3, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (7, 'Sugar - Cubes', 66516, 'Displ spiral fx shaft of l femr, 7thN', 19, 4, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (8, 'Ocean Spray - Ruby Red', 35380, 'Malignant neoplasm of vagina', 1, 2, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (9, 'Water - Tonic', 50105, 'Right upper quadrant pain', 7, 3, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (10, 'Bread - Sour Batard', 22819, 'Varicose veins of left lower extremity with ulcer of thigh', 30, 4, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (11, 'Peppercorns - Green', 73104, 'Oth intentional self-harm by drowning and submersion, init', 7, 4, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (12, 'Blueberries - Frozen', 22292, 'Bennett''s fracture, unspecified hand, sequela', 20, 4, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (13, 'Crab - Dungeness, Whole, live', 16561, 'Other specified injuries of left ankle, initial encounter', 43, 3, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (14, 'Parsley - Dried', 94722, 'Other specified crystal arthropathies, vertebrae', 18, 2, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (15, 'Potatoes - Mini Red', 78355, 'Torus fx upper end of left tibia, subs for fx w malunion', 25, 1, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (16, 'Grenadine', 71033, 'Underdosing of macrolides, subsequent encounter', 17, 1, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (17, 'Creme De Menth - White', 19569, 'Diseases of the resp sys comp pregnancy, first trimester', 1, 2, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (18, 'Ham - Procutinni', 25756, 'Sltr-haris Type IV physeal fx upper end of left tibia', 49, 3, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (19, 'Tea - Herbal Sweet Dreams', 15017, 'Injury of right uterine artery, subsequent encounter', 36, 4, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (20, 'Plate - Foam, Bread And Butter', 72799, 'Adverse effect of unsp agents aff the cardiovascular sys', 24, 4, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (21, 'Pasta - Orzo, Dry', 74686, 'Retinal artery branch occlusion', 1, 2, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (22, 'Cheese - Shred Cheddar / Mozza', 23538, 'Whole chromosome monosomy,nonmosaic (meiotic nondisjunction)', 17, 3, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (23, 'Flour - Masa De Harina Mexican', 32319, 'Laceration of other blood vessels of thorax, left side', 48, 2, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (24, 'Five Alive Citrus', 6520, 'Traum hemor left cerebrum w LOC of 30 minutes or less', 36, 3, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (25, 'Beef - Bones, Marrow', 50652, 'Milt op w unarmed hand to hand combat, civilian, subs', 7, 4, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (26, 'Bread - French Stick', 28689, 'Thrombosis due to vascular prosth dev/grft, sequela', 33, 1, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (27, 'Flavouring - Rum', 76135, 'Unsp opn wnd left lesser toe(s) w/o damage to nail, sequela', 2, 2, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (28, 'Tart - Pecan Butter Squares', 43238, 'Nondisplaced spiral fracture of shaft of right femur, init', 1, 3, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (29, 'Beer - Blue', 43980, 'Abrasion, unspecified foot', 50, 2, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (30, 'Wine - Red, Colio Cabernet', 4787, 'Poisoning by other psychotropic drugs, assault', 49, 4, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (31, 'Duck - Legs', 28620, 'Gastric contents in esoph causing comprsn of trachea, subs', 13, 4, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (32, 'Puff Pastry - Slab', 77864, 'Gangosa', 9, 3, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (33, 'Yogurt - Plain', 73880, 'Frostbite with tissue necrosis of right foot, sequela', 6, 3, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (34, 'Tart Shells - Savory, 3', 16005, 'Unsp injury of femoral artery, unspecified leg, subs encntr', 21, 3, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (35, 'Chinese Foods - Thick Noodles', 61215, 'Hydroxyapatite deposition disease, left wrist', 45, 4, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (36, 'Wine - Red, Cooking', 98306, 'Amebic cystitis', 11, 3, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (37, 'Wine - Blue Nun Qualitatswein', 44570, 'Malignant otitis externa, left ear', 20, 3, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (38, 'Cheese - Cheddar, Medium', 54213, 'Other specified disorders of teeth and supporting structures', 24, 3, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (39, 'Beans - Butter Lrg Lima', 80892, 'Sedatv/hyp/anxiolytc dependence w anxiety disorder', 25, 4, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (40, 'Durian Fruit', 79156, 'Injury of olfactory [1st ] nerve, unspecified side', 16, 4, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (41, 'Flour - Buckwheat, Dark', 31263, 'Displacement of int fix of right femur, subs', 13, 1, 3);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (42, 'Mix - Cappucino Cocktail', 10647, 'Urethral caruncle', 41, 1, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (43, 'Eel Fresh', 84856, 'Transient synovitis, right elbow', 23, 3, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (44, 'Easy Off Oven Cleaner', 45017, 'Unspecified injury of left ankle, subsequent encounter', 25, 3, 2);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (45, 'Onions - Cippolini', 21521, 'Drug/chem diab w severe nonprlf diab rtnop w/o macular edema', 24, 3, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (46, 'Turkey Tenderloin Frozen', 27889, 'Nondisp fx of capitate bone, unspecified wrist, sequela', 25, 2, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (47, 'Garbag Bags - Black', 57714, 'Pressure ulcer of right elbow, stage 3', 45, 3, 1);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (48, 'Cup - 6oz, Foam', 80899, 'Sltr-haris Type II physl fx lower end ulna, right arm, init', 13, 4, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (49, 'Dikon', 67756, 'Oth stimulant dependence with oth stimulant-induced disorder', 19, 3, 4);
insert into product (id, product_name, price, specification, quantity, category_id, brand_id) values (50, 'Wine - Red, Colio Cabernet', 31880, 'Nondisp fx of low epiphy (separation) of l femr, 7thP', 4, 3, 4);
